-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-28 02:51:05 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

SET ECHO ON
SPOOL wc_schema_output.txt

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE cruise_port CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE passenger_address CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE port_temp CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

DROP TABLE tour_language CASCADE CONSTRAINTS;

DROP TABLE tour_report CASCADE CONSTRAINTS;

DROP TABLE tour_report_entry CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cabin (
    ship_code      NUMBER(5) NOT NULL,
    cabin_no       NUMBER(4) NOT NULL,
    cabin_capacity NUMBER(1) NOT NULL,
    cabin_class    CHAR(1 CHAR) NOT NULL
);

ALTER TABLE cabin
    ADD CONSTRAINT "CONSTRAINT CABIN CLASS" CHECK ( cabin_class IN ( 'B', 'I', 'O', 'S' ) );

COMMENT ON COLUMN cabin.ship_code IS
    'Ship''s code';

COMMENT ON COLUMN cabin.cabin_no IS
    'The number that uniquely identifies the cabin';

COMMENT ON COLUMN cabin.cabin_capacity IS
    'The capacity of the cabin';

COMMENT ON COLUMN cabin.cabin_class IS
    'The class of the cabin';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_no,
                                                        ship_code );

CREATE TABLE country (
    country_code CHAR(2 CHAR) NOT NULL,
    country_name VARCHAR2(60 CHAR) NOT NULL
);

COMMENT ON COLUMN country.country_code IS
    'Country''s code';

COMMENT ON COLUMN country.country_name IS
    'Country''s name';

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE cruise (
    cruise_id   NUMBER(4) NOT NULL,
    cruise_name VARCHAR2(50 CHAR) NOT NULL,
    ship_code   NUMBER(5) NOT NULL,
    cruise_desc VARCHAR2(99 CHAR) NOT NULL
);

COMMENT ON COLUMN cruise.cruise_id IS
    'The ID that uniquely identifies the cruise';

COMMENT ON COLUMN cruise.cruise_name IS
    'The name of the cruise';

COMMENT ON COLUMN cruise.ship_code IS
    'Ship''s code';

COMMENT ON COLUMN cruise.cruise_desc IS
    'A brief description of the cruise';

ALTER TABLE cruise ADD CONSTRAINT cruise_pk PRIMARY KEY ( cruise_id );

CREATE TABLE cruise_port (
    cruise_id   NUMBER(4) NOT NULL,
    port_code   CHAR(5 CHAR) NOT NULL,
    cp_datetime DATE NOT NULL
);

COMMENT ON COLUMN cruise_port.cruise_id IS
    'The ID that uniquely identifies the cruise';

COMMENT ON COLUMN cruise_port.port_code IS
    'The code that uniquely identifies the port';

COMMENT ON COLUMN cruise_port.cp_datetime IS
    'The arrival and departure datetime';

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_port_pk PRIMARY KEY ( cruise_id,
                                                cp_datetime,
                                                port_code );

CREATE TABLE language (
    language_code CHAR(2 CHAR) NOT NULL,
    language_name VARCHAR2(25 CHAR) NOT NULL
);

COMMENT ON COLUMN language.language_code IS
    'Language code stored in ISO 639-1 Alpha-2 format';

COMMENT ON COLUMN language.language_name IS
    'The name of the language';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( language_code );

CREATE TABLE manifest (
    cruise_id             NUMBER(4) NOT NULL,
    passenger_id          NUMBER(5) NOT NULL,
    ship_code             NUMBER(5) NOT NULL,
    cabin_no              NUMBER(4) NOT NULL,
    man_boarding_datetime DATE NOT NULL
);

COMMENT ON COLUMN manifest.cruise_id IS
    'The ID that uniquely identifies the cruise';

COMMENT ON COLUMN manifest.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN manifest.ship_code IS
    'Ship''s code';

COMMENT ON COLUMN manifest.cabin_no IS
    'The number that uniquely identifies the cabin';

COMMENT ON COLUMN manifest.man_boarding_datetime IS
    'The passenger''s boarding date and time';

ALTER TABLE manifest ADD CONSTRAINT manifest_pk PRIMARY KEY ( passenger_id,
                                                              cruise_id );

CREATE TABLE operator (
    operator_id       NUMBER(5) NOT NULL,
    operator_name     VARCHAR2(50 CHAR) NOT NULL,
    operator_ceo_name VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON COLUMN operator.operator_id IS
    'Operator''s ID';

COMMENT ON COLUMN operator.operator_name IS
    'Operator''s name';

COMMENT ON COLUMN operator.operator_ceo_name IS
    'Operator''s company CEO name';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( operator_id );

CREATE TABLE passenger (
    passenger_id       NUMBER(5) NOT NULL,
    passenger_fname    VARCHAR2(50 CHAR),
    passenger_lname    VARCHAR2(50 CHAR),
    passenger_gender   CHAR(1 CHAR) NOT NULL,
    passenger_dob      DATE NOT NULL,
    passenger_phone_no VARCHAR2(15 CHAR),
    guardian_id        NUMBER(5),
    pa_id              NUMBER(5) NOT NULL,
    passenger_lang     CHAR(2 CHAR) NOT NULL
);

ALTER TABLE passenger
    ADD CONSTRAINT "CONSTRAINT PASSENGER GENDER" CHECK ( passenger_gender IN ( 'F', 'M',
    'O' ) );

COMMENT ON COLUMN passenger.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.passenger_fname IS
    'Passenger''s first name';

COMMENT ON COLUMN passenger.passenger_lname IS
    'Passenger''s last name';

COMMENT ON COLUMN passenger.passenger_gender IS
    'Passenger''s gender';

COMMENT ON COLUMN passenger.passenger_dob IS
    'Passenger''s date of birth';

COMMENT ON COLUMN passenger.passenger_phone_no IS
    'Passenger''s phone number';

COMMENT ON COLUMN passenger.guardian_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.pa_id IS
    'Address ID';

COMMENT ON COLUMN passenger.passenger_lang IS
    'Language code stored in ISO 639-1 Alpha-2 format';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( passenger_id );

CREATE TABLE passenger_address (
    pa_id           NUMBER(5) NOT NULL,
    pa_street       VARCHAR2(99 CHAR) NOT NULL,
    pa_town         VARCHAR2(99 CHAR) NOT NULL,
    pa_postcode     VARCHAR2(10 CHAR) NOT NULL,
    pa_country_code CHAR(2 CHAR) NOT NULL
);

COMMENT ON COLUMN passenger_address.pa_id IS
    'Address ID';

COMMENT ON COLUMN passenger_address.pa_street IS
    'Street address';

COMMENT ON COLUMN passenger_address.pa_town IS
    'The town the address belongs to';

COMMENT ON COLUMN passenger_address.pa_postcode IS
    'Postcode';

COMMENT ON COLUMN passenger_address.pa_country_code IS
    'Country''s code';

ALTER TABLE passenger_address ADD CONSTRAINT address_pk PRIMARY KEY ( pa_id );

ALTER TABLE passenger_address
    ADD CONSTRAINT address_nk UNIQUE ( pa_street,
                                       pa_town,
                                       pa_postcode );

CREATE TABLE port (
    port_code       CHAR(5 CHAR) NOT NULL,
    country_code    CHAR(2 CHAR) NOT NULL,
    port_name       VARCHAR2(50 CHAR) NOT NULL,
    port_population NUMBER(9) NOT NULL,
    port_longitude  NUMBER(10, 7) NOT NULL,
    port_latitude   NUMBER(9, 7) NOT NULL
);

ALTER TABLE port
    ADD CONSTRAINT "CONSTRAINT PORT LONGITUDE" CHECK ( port_longitude BETWEEN - 180 AND
    180 );

ALTER TABLE port
    ADD CONSTRAINT "CONSTRAINT PORT LATITUDE" CHECK ( port_latitude BETWEEN - 90 AND 90 );

COMMENT ON COLUMN port.port_code IS
    'The code that uniquely identifies the port';

COMMENT ON COLUMN port.country_code IS
    'Country''s code';

COMMENT ON COLUMN port.port_name IS
    'The name of the port';

COMMENT ON COLUMN port.port_population IS
    'The population count of the port';

COMMENT ON COLUMN port.port_longitude IS
    'The longitude location of the port';

COMMENT ON COLUMN port.port_latitude IS
    'The latitude location of the port';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE port_temp (
    port_code   CHAR(5 CHAR) NOT NULL,
    pt_month    CHAR(3 CHAR) NOT NULL,
    pt_avg_high NUMBER(2) NOT NULL,
    pt_avg_low  NUMBER(2) NOT NULL
);

ALTER TABLE port_temp
    ADD CONSTRAINT "CONSTRAINT PT_MONTH" CHECK ( pt_month IN ( 'Apr', 'Aug', 'Dec', 'Feb',
    'Jan',
                                                               'Jul', 'Jun', 'Mar', 'May',
                                                               'Nov',
                                                               'Oct', 'Sep' ) );

COMMENT ON COLUMN port_temp.port_code IS
    'The code that uniquely identifies the port';

COMMENT ON COLUMN port_temp.pt_month IS
    'The recorded month';

COMMENT ON COLUMN port_temp.pt_avg_high IS
    'Port''s temperature (average high)';

COMMENT ON COLUMN port_temp.pt_avg_low IS
    'Port''s temperature (average low)';

ALTER TABLE port_temp ADD CONSTRAINT port_temp_pk PRIMARY KEY ( pt_month,
                                                                port_code );

CREATE TABLE ship (
    ship_code               NUMBER(5) NOT NULL,
    ship_name               VARCHAR2(50 CHAR) NOT NULL,
    ship_commission_date    DATE NOT NULL,
    ship_tonnage            NUMBER(7) NOT NULL,
    ship_max_guest_capacity NUMBER(4) NOT NULL,
    operator_id             NUMBER(5) NOT NULL,
    country_of_registration CHAR(2 CHAR) NOT NULL
);

COMMENT ON COLUMN ship.ship_code IS
    'Ship''s code';

COMMENT ON COLUMN ship.ship_name IS
    'The name of the ship';

COMMENT ON COLUMN ship.ship_commission_date IS
    'The date the ship was commissioned';

COMMENT ON COLUMN ship.ship_tonnage IS
    'The ship''s tonnage';

COMMENT ON COLUMN ship.ship_max_guest_capacity IS
    'The maximum number of guest the ship can accept';

COMMENT ON COLUMN ship.operator_id IS
    'Operator''s ID';

COMMENT ON COLUMN ship.country_of_registration IS
    'Country''s code';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE tour (
    tour_id               NUMBER(6) NOT NULL,
    port_code             CHAR(5 CHAR) NOT NULL,
    tour_no               NUMBER(1) NOT NULL,
    tour_name             VARCHAR2(50 CHAR) NOT NULL,
    tour_desc             VARCHAR2(99 CHAR) NOT NULL,
    tour_hrs_req          NUMBER(3, 1) NOT NULL,
    tour_cost             NUMBER(3) NOT NULL,
    tour_wc_access        CHAR(1 CHAR) NOT NULL,
    tour_availability     VARCHAR2(70 CHAR) NOT NULL,
    tour_start_time       DATE NOT NULL,
    tour_min_participants NUMBER(5) NOT NULL
);

ALTER TABLE tour ADD CHECK ( tour_hrs_req BETWEEN 0 AND 24 );

COMMENT ON COLUMN tour.tour_id IS
    'Tour''s ID';

COMMENT ON COLUMN tour.port_code IS
    'The code that uniquely identifies the port';

COMMENT ON COLUMN tour.tour_no IS
    'Tour number';

COMMENT ON COLUMN tour.tour_name IS
    'Tour''s short description';

COMMENT ON COLUMN tour.tour_desc IS
    'A brief description of the tour';

COMMENT ON COLUMN tour.tour_hrs_req IS
    'The hours requirement of the tour';

COMMENT ON COLUMN tour.tour_cost IS
    'The cost per person of the tour';

COMMENT ON COLUMN tour.tour_wc_access IS
    'The tour''s wheelchair access';

COMMENT ON COLUMN tour.tour_availability IS
    'The interval of which the tour is available';

COMMENT ON COLUMN tour.tour_start_time IS
    'The start time of the tour';

COMMENT ON COLUMN tour.tour_min_participants IS
    'Minimum number of participants that must be hit before the tour will be hosted';

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_id );

ALTER TABLE tour ADD CONSTRAINT tour_nk UNIQUE ( tour_no,
                                                 port_code );

CREATE TABLE tour_language (
    tour_id       NUMBER(6) NOT NULL,
    language_code CHAR(2 CHAR) NOT NULL
);

COMMENT ON COLUMN tour_language.tour_id IS
    'Tour''s ID';

COMMENT ON COLUMN tour_language.language_code IS
    'Language code stored in ISO 639-1 Alpha-2 format';

ALTER TABLE tour_language ADD CONSTRAINT tour_language_pk PRIMARY KEY ( language_code,
                                                                        tour_id );

CREATE TABLE tour_report (
    tour_id   NUMBER(6) NOT NULL,
    tour_date DATE NOT NULL
);

COMMENT ON COLUMN tour_report.tour_id IS
    'Tour''s ID';

COMMENT ON COLUMN tour_report.tour_date IS
    'The date of the tour';

ALTER TABLE tour_report ADD CONSTRAINT tour_report_pk PRIMARY KEY ( tour_date,
                                                                    tour_id );

CREATE TABLE tour_report_entry (
    tour_id      NUMBER(6) NOT NULL,
    tour_date    DATE NOT NULL,
    passenger_id NUMBER(5) NOT NULL,
    cruise_id    NUMBER(4) NOT NULL,
    pay_received CHAR(1 CHAR) NOT NULL
);

ALTER TABLE tour_report_entry
    ADD CONSTRAINT "CONSTRAINT PAY RECEIVED" CHECK ( pay_received IN ( 'N', 'Y' ) );

COMMENT ON COLUMN tour_report_entry.tour_id IS
    'Tour''s ID';

COMMENT ON COLUMN tour_report_entry.tour_date IS
    'The date of the tour';

COMMENT ON COLUMN tour_report_entry.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN tour_report_entry.cruise_id IS
    'The ID that uniquely identifies the cruise';

COMMENT ON COLUMN tour_report_entry.pay_received IS
    'Indicates whether the payment has been received';

ALTER TABLE tour_report_entry
    ADD CONSTRAINT tour_report_entry_pk PRIMARY KEY ( tour_date,
                                                      tour_id,
                                                      passenger_id );

ALTER TABLE passenger_address
    ADD CONSTRAINT address_country FOREIGN KEY ( pa_country_code )
        REFERENCES country ( country_code );

ALTER TABLE passenger
    ADD CONSTRAINT address_passenger FOREIGN KEY ( pa_id )
        REFERENCES passenger_address ( pa_id );

ALTER TABLE manifest
    ADD CONSTRAINT cabin_manifest FOREIGN KEY ( cabin_no,
                                                ship_code )
        REFERENCES cabin ( cabin_no,
                           ship_code );

ALTER TABLE port
    ADD CONSTRAINT country_port FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE ship
    ADD CONSTRAINT country_ship FOREIGN KEY ( country_of_registration )
        REFERENCES country ( country_code );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_cp FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE manifest
    ADD CONSTRAINT cruise_manifest FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE tour_report_entry
    ADD CONSTRAINT cruise_tre FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE passenger
    ADD CONSTRAINT guardian_passenger FOREIGN KEY ( guardian_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE passenger
    ADD CONSTRAINT language_passenger FOREIGN KEY ( passenger_lang )
        REFERENCES language ( language_code );

ALTER TABLE tour_language
    ADD CONSTRAINT language_tl FOREIGN KEY ( language_code )
        REFERENCES language ( language_code );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( operator_id )
        REFERENCES operator ( operator_id );

ALTER TABLE manifest
    ADD CONSTRAINT passenger_manifest FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE tour_report_entry
    ADD CONSTRAINT passenger_tre FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE cruise_port
    ADD CONSTRAINT port_cp FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE port_temp
    ADD CONSTRAINT port_pt FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE tour
    ADD CONSTRAINT port_tour FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE cabin
    ADD CONSTRAINT ship_cabin FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE cruise
    ADD CONSTRAINT ship_cruise FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE tour_language
    ADD CONSTRAINT tour_tl FOREIGN KEY ( tour_id )
        REFERENCES tour ( tour_id );

ALTER TABLE tour_report
    ADD CONSTRAINT tour_tr FOREIGN KEY ( tour_id )
        REFERENCES tour ( tour_id );

ALTER TABLE tour_report_entry
    ADD CONSTRAINT tr_tre FOREIGN KEY ( tour_date,
                                        tour_id )
        REFERENCES tour_report ( tour_date,
                                 tour_id );

SPOOL OFF
SET ECHO OFF

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             0
-- ALTER TABLE                             47
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
